import type { Metadata } from 'next';

import Container from '@/components/grid/Container';
import Row from '@/components/grid/Row';
import Col from '@/components/grid/Col';
import Text from '@/components/typography/Text';
import Paragraph from '@/components/typography/Paragraph';
import Title from '@/components/typography/Title';
import Link from '@/components/typography/Link';
import Icon from '@/components/Icon';
import Button from '@/components/Button';
import Tooltip from '@/components/floating/Tooltip';
import styles from './page.module.css';
import Input from '@/components/form/Input';
import ModalDialog from '@/components/modal/ModalDialog';
import InputNumber from '@/components/form/InputNumber';
import Flex from '@/components/Flex';
import Card from '@/components/Card';

// import CheckoutTotalResult from '@/features/checkout/components/CheckoutTotalResult';

// import { checkoutGetDetails } from '@/features/checkout/routes';

export const metadata: Metadata = {
    title: 'Оформление заказа',
    description: 'Generated by create next app',
};

export default async function Contacts() {
    // const response = await checkoutGetDetails();
    // if (!response.isSuccess) {
    //     throw new Error('Ошибка при загрузке страницы');
    // }
    // const checkout = response.data;

    // const isHasAccount = false;

    return (
        <main>
            <Container>
                <Row>
                    {/* <Col md={9}>
                        <Flex direction="column" gapY="md">
                            <Card>
                                <Title level={2}>Способ доставки</Title>
                                <div>

                                </div>
                            </Card>
                            <Card>
                                <Title level={2}>Способ оплаты</Title>
                                <div>
                                    
                                </div>
                            </Card>
                            <Card>
                                <Title level={2}>Мои данные</Title>
                                <div>
                                    {
                                        checkout.user.fio && checkout.user.phone ? 
                                        <div></div>
                                        :
                                        <div></div>
                                    }
                                </div>
                            </Card>
                            <Card>
                                <Title level={2}>Ожидаемая дата доставки: TODO OZON</Title>
                            </Card>
                        </Flex>
                    </Col>
                    <Col md={3}>
                        <CheckoutTotalResult />
                    </Col> */}
                </Row>
            </Container>
        </main>
    );
}
