import type { Metadata } from 'next';

import type { Product } from '@/features/product/typings';

import Container from '@/components/grid/Container';
import Row from '@/components/grid/Row';
import Col from '@/components/grid/Col';
import Text from '@/components/typography/Text';
import Paragraph from '@/components/typography/Paragraph';
import Title from '@/components/typography/Title';
import Link from '@/components/typography/Link';
import Icon from '@/components/Icon';
import Empty from '@/components/Empty';
import Result from '@/components/Result';
import Button from '@/components/Button';
import Tooltip from '@/components/floating/Tooltip';
import TextBlock from '@/widgets/TextBlock/TextBlock';
import Input from '@/components/form/Input';
import ModalDialog from '@/components/modal/ModalDialog';
import InputNumber from '@/components/form/InputNumber';
import Flex from '@/components/Flex';
import Breadcrumbs from '@/components/Breadcrumbs';

import BasketList from '@/features/basket/components/BasketList';
import BasketTotalResult from '@/features/basket/components/BasketTotalResult';

import styles from './page.module.css';

const products: Array<Product> = [];

export const metadata: Metadata = {
    title: 'Моя корзина',
    description: 'Generated by create next app',
};

export default function Basket() {
    return (
        <main>
            <Container className="mt-md">
                <Title level={1} className="mb-xs">
                    Корзина
                </Title>
                {/* TODO
                <Banner
                    title="The papier promise"
                    content="if you are not 100% happy"
                /> */}
                <Row>
                    <Col md={9}>
                        <BasketList />
                    </Col>
                    <Col md={3}>
                        <BasketTotalResult />
                    </Col>
                </Row>
            </Container>
        </main>
    );
}
