import type { Metadata } from 'next';

import Container from '@/components/grid/Container';
import Row from '@/components/grid/Row';
import Col from '@/components/grid/Col';
import Text from '@/components/typography/Text';
import Paragraph from '@/components/typography/Paragraph';
import Title from '@/components/typography/Title';
import Link from '@/components/typography/Link';
import Icon from '@/components/Icon';
import Empty from '@/components/Empty';
import Result from '@/components/Result';
import Button from '@/components/Button';
import Tooltip from '@/components/floating/Tooltip';
import styles from './page.module.css';
import Input from '@/components/form/Input';
import ModalDialog from '@/components/modal/ModalDialog';
import Table from '@/components/Table';
import Flex from '@/components/Flex';

import PaymentListFilters from '@/features/payment/components/PaymentListFilters';

import type { PageProps, SearchParams } from '@/typings';
import type { TableColumnsFor } from '@/components/Table';

import { parseSearchParams as psp } from '@/utils/actions/search-params';

import { paymentGetAll } from '@/features/payment/routes';

export const metadata: Metadata = {
    title: 'Админпанель | Баланс',
    description: 'Generated by create next app',
};

const getPayments = async (params?: SearchParams) => {
    const response = await paymentGetAll({
        page: psp.integer(params?.page) || 1,
        paymentId: psp.integer(params?.paymentId),
    });
    if (!response.isSuccess) {
        throw new Error('Ошибка при загрузке страницы');
    }

    return response.data;
};

const columns: TableColumnsFor<typeof getPayments> = [
    {
        title: 'ID',
        render: ({ id }) => id,
    },
    {
        title: 'Инициатор',
        render: ({ fio }) => fio,
    },
    {
        title: 'Статус',
        render: ({ status }) => status,
    },
    {
        title: 'Дата',
        render: ({ createdAt }) => createdAt,
    },
    {
        title: 'Действия',
        render: ({ id }) => (
            <Button href={`/admin/payment/${id}`} variant="link" size="sm">
                Подробнее
            </Button>
        ),
    },
];

export default async function Payment(props: PageProps) {
    const payments = await getPayments(props.searchParams);

    return (
        <main>
            <Container className="mt-lg">
                <PaymentListFilters />
                <Table columns={columns} data={payments} />
            </Container>
        </main>
    );
}
