import Container from '@/components/grid/Container';
import Row from '@/components/grid/Row';
import Col from '@/components/grid/Col';
import Text from '@/components/typography/Text';
import Paragraph from '@/components/typography/Paragraph';
import Title from '@/components/typography/Title';
import Link from '@/components/typography/Link';
import Icon from '@/components/Icon';
import Button from '@/components/Button';
import Tooltip from '@/components/floating/Tooltip';
import styles from './page.module.css';
import type { Metadata } from 'next';
import TextBlock from '@/widgets/TextBlock/TextBlock';
import Input from '@/components/form/Input';
import ModalDialog from '@/components/modal/ModalDialog';
import InputNumber from '@/components/form/InputNumber';
import Flex from '@/components/Flex';

import BannerBlock from '@/widgets/BannerBlock';

export const metadata: Metadata = {
    title: 'Получить скидку',
    description: 'Generated by create next app',
};
export default function Contacts() {
    return (
        <main>
            <BannerBlock
                image={{
                    src: 'https://dummyimage.com/800x800/f4eee0/ab7c0d&text=1',
                }}
                title="Get 15% Off"
                before={<Text>NEWSLETTER</Text>}
                content={
                    <div>
                        <ol>
                            <li>Subscribe below</li>
                            <li>Receive an email with the 15% off code</li>
                            <li>Order & enjoy the benefits of plant healing 🌿</li>
                        </ol>
                        <Input placeholder="Name" />
                        <Input placeholder="Email" />
                        <Button>JOIN</Button>
                    </div>
                }
                reverse
            />
        </main>
    );
}
