import type { Metadata } from 'next';

import Container from '@/components/grid/Container';
import Row from '@/components/grid/Row';
import Col from '@/components/grid/Col';
import Text from '@/components/typography/Text';
import Paragraph from '@/components/typography/Paragraph';
import Title from '@/components/typography/Title';
import Link from '@/components/typography/Link';
import Icon from '@/components/Icon';
import Empty from '@/components/Empty';
import Result from '@/components/Result';
import Button from '@/components/Button';
import Tooltip from '@/components/floating/Tooltip';
import styles from './page.module.css';
import Input from '@/components/form/Input';
import ModalDialog from '@/components/modal/ModalDialog';
import Table from '@/components/Table';
import Flex from '@/components/Flex';

import UserListFilters from '@/features/user/components/UserListFilters';

import type { PageProps, SearchParams } from '@/typings';
import type { TableColumnsFor } from '@/components/Table';

import { formatPhoneNumber } from '@/utils/text';
import { parseSearchParams as psp } from '@/utils/actions/search-params';

import { userGetAll } from '@/features/user/routes';

export const metadata: Metadata = {
    title: 'Админпанель | Пользователи',
    description: 'Generated by create next app',
};

const getUsers = async (params?: SearchParams) => {
    const response = await userGetAll({
        page: psp.integer(params?.page) || 1,
        userId: psp.integer(params?.userId),
        email: psp.string(params?.email),
        phone: psp.string(params?.phone),
    });
    if (!response.isSuccess) {
        throw new Error('Ошибка при загрузке страницы');
    }

    return response.data;
};

const columns: TableColumnsFor<typeof getUsers> = [
    {
        title: 'ID',
        render: ({ id }) => id,
    },
    {
        title: 'Email',
        render: ({ email }) => (email ? <a href={`mailto:+${email}`}>{email}</a> : '—'),
    },
    {
        title: 'Телефон',
        render: ({ phone }) =>
            phone ? <a href={`tel:+${phone}`}>{formatPhoneNumber(phone)}</a> : '—',
    },
    {
        title: 'ФИО',
        render: ({ fio }) => fio,
    },
    {
        title: 'Действия',
        render: ({ id }) => (
            <Button href={`/admin/user/${id}`} variant="link" size="sm">
                Подробнее
            </Button>
        ),
    },
];

export default async function User(props: PageProps) {
    const users = await getUsers(props.searchParams);

    return (
        <main>
            <Container className="mt-lg">
                <UserListFilters />
                <Table columns={columns} data={users} />
            </Container>
        </main>
    );
}
