import Image from 'next/image';
import Container from '@/components/grid/Container';
import Row from '@/components/grid/Row';
import Col from '@/components/grid/Col';
import Text from '@/components/typography/Text';
import Paragraph from '@/components/typography/Paragraph';
import Title from '@/components/typography/Title';
import Link from '@/components/typography/Link';
import Icon from '@/components/Icon';
import Empty from '@/components/Empty';
import Button from '@/components/Button';
import Tooltip from '@/components/floating/Tooltip';
import FaqBlock from '@/widgets/FaqBlock';
import SliderBlock from '@/widgets/SliderBlock';
import ContactBlock from '@/widgets/ContactBlock';

import Input from '@/components/form/Input';
import ModalSlider from '@/components/modal/ModalSlider';
import InputNumber from '@/components/form/InputNumber';
import ProductList from '@/features/product/components/ProductList';

import styles from './page.module.css';

import type { Metadata } from 'next';
import type { QuestionType } from '@/widgets/FaqBlock';
import type { Product } from '@/features/product/typings';
import type { SlideType } from '@/widgets/SliderBlock';

export const metadata: Metadata = {
    title: 'Моя первая страница',
    description: 'Generated by create next app',
};

const questions: Array<QuestionType> = [
    {
        question: 'asd',
        answer: 'asd',
    },
    {
        question: 'asd',
        answer: 'asd',
    },
    {
        question: 'asd',
        answer: 'asd',
    },
];

const products: Array<Product> = [
    {
        id: 1,
        name: 'Маникюр (без покрытия)',
        price: 800,
        offer: null,
        images: [],
        chips: [],
    },
    {
        id: 2,
        name: 'Маникюр (без покрытия)',
        price: 800,
        offer: null,
        images: [],
        chips: [],
    },
    {
        id: 3,
        name: 'Маникюр (без покрытия)',
        price: 800,
        offer: null,
        images: [],
        chips: [],
    },
    {
        id: 4,
        name: 'Маникюр (без покрытия)',
        price: 800,
        offer: null,
        images: [],
        chips: [],
    },
    {
        id: 5,
        name: 'Маникюр (без покрытия)',
        price: 800,
        offer: null,
        images: [],
        chips: [],
    },
];

const slides: Array<SlideType> = [
    {
        image: 'https://cdn.sanity.io/images/jxk2yin1/production/518dface31a446e1b23c459d64df128ac1ef16b1-5464x8192.jpg?auto=format&fit=max&q=85&rect=0,0,5464,6406&w=5464',
        title: 'test',
        description: 'asdjasdkl',
    },
    {
        image: 'https://cdn.sanity.io/images/jxk2yin1/production/927d5631a0e978f4385cede3b215bb7b27123dff-5597x3731.jpg?auto=format&fit=max&q=85&w=5597',
        title: 'test',
        description: 'asdjasdkl',
    },
];

export default function Home() {
    return (
        <main>
            <SliderBlock slides={slides} />
            <ProductList title="Услуги" products={products} />
            <FaqBlock title="Часто задаваемые вопросы" questions={questions} />
            <ContactBlock />
        </main>
    );
}
