import Container from '@/components/grid/Container';
import Row from '@/components/grid/Row';
import Col from '@/components/grid/Col';
import Text from '@/components/typography/Text';
import Paragraph from '@/components/typography/Paragraph';
import Title from '@/components/typography/Title';
import Link from '@/components/typography/Link';
import Icon from '@/components/Icon';
import Empty from '@/components/Empty';
import Result from '@/components/Result';
import Button from '@/components/Button';
import Tooltip from '@/components/floating/Tooltip';
import Input from '@/components/form/Input';
import InputNumber from '@/components/form/InputNumber';
import ModalDialog from '@/components/modal/ModalDialog';
import Flex from '@/components/Flex';
import Chip from '@/components/Chip';
import Table from '@/components/Table';

import { MdOutlineAccountCircle } from 'react-icons/md';

import StylePalette from '@/features/style/components/StylePalette';

import type { Metadata } from 'next';

import styles from './page.module.scss';
import classNames from 'classnames';

export const metadata: Metadata = {
    title: 'Стиль',
    description: 'Generated by create next app',
};

export default function StyleGuide() {
    return (
        <main>
            <Container>
                <div className={styles.container}>
                    <section className={classNames(styles.section, styles.colors)}>
                        <div className={styles.title}>colors</div>
                        <StylePalette className="mt-md" color="primary" />
                        <StylePalette className="mt-md" color="secondary" />
                        <StylePalette className="mt-md" color="success" />
                        <StylePalette className="mt-md" color="danger" />
                        <StylePalette className="mt-md" color="info" />
                    </section>

                    <section className={classNames(styles.section, styles.typography)}>
                        <div className={styles.title}>typography</div>
                        <Row>
                            <Col md={5}>
                                <Title level={1} family="plex-serif">
                                    Aa
                                </Title>
                                <Text family="plex-serif">Plex-Serif</Text>
                            </Col>
                            <Col md={7}>
                                <Title level={1} family="plex-sans">
                                    Aa
                                </Title>
                                <Text family="plex-sans">Plex-Sans</Text>
                            </Col>
                        </Row>
                        <Row className="mt-lg">
                            <Col md={5}>
                                <div className={styles.subtitle}>Headlines</div>
                                <Title level={1}>h1 headline</Title>
                                <Title level={2}>h2 headline</Title>
                                <Title level={3}>h3 headline</Title>
                                <Title level={4}>h4 headline</Title>
                                <Title level={5}>h5 headline</Title>
                            </Col>
                            <Col md={7}>
                                <div className={styles.subtitle}>Body Text</div>
                                <Paragraph className="mb-md">
                                    I think we need to start from scratch. Jazz it up a little bit-
                                    use a funky color like purple.
                                </Paragraph>
                                <Paragraph className="mb-md" bold>
                                    Can you add a bit of pastel pink and baby blue because the
                                    purple alone looks too fancy.
                                </Paragraph>
                                <Paragraph className="mb-md" italic>
                                    Make the purple more well, purple-er. Try a more powerful
                                    colour, it needs to be the same, but totally different.
                                </Paragraph>
                            </Col>
                        </Row>
                    </section>

                    <section className={classNames(styles.section, styles.buttons)}>
                        <div className={styles.title}>buttons</div>
                        <div className={styles.subtitle}>Variant</div>
                        <div>
                            <Button variant="outlined" className="mx-sm">
                                outlined
                            </Button>
                            <Button variant="filled" className="mx-sm">
                                filled
                            </Button>
                            <Button variant="text" className="mx-sm">
                                text
                            </Button>
                            <Button variant="link" className="mx-sm">
                                link
                            </Button>
                        </div>
                        <div className={styles.subtitle}>Shape</div>
                        <div>
                            <Button shape="squre" className="mx-sm">
                                squre
                            </Button>
                            <Button shape="round" className="mx-sm">
                                round
                            </Button>
                            <Button
                                shape="circle"
                                className="mx-sm"
                                icon={<MdOutlineAccountCircle />}
                            />
                        </div>
                        <div className={styles.subtitle}>Color</div>
                        <div>
                            <Button color="dark" className="mx-sm">
                                dark
                            </Button>
                            <Button color="primary" className="mx-sm">
                                primary
                            </Button>
                            <Button color="success" className="mx-sm">
                                success
                            </Button>
                            <Button color="danger" className="mx-sm">
                                danger
                            </Button>
                            <Button color="info" className="mx-sm">
                                info
                            </Button>
                        </div>
                        <div className={styles.subtitle}>Disabled</div>
                        <div>
                            <Button variant="outlined" disabled className="mx-sm">
                                outlined
                            </Button>
                            <Button variant="filled" disabled className="mx-sm">
                                filled
                            </Button>
                            <Button variant="text" disabled className="mx-sm">
                                text
                            </Button>
                            <Button variant="link" disabled className="mx-sm">
                                link
                            </Button>
                        </div>
                        <div className={styles.subtitle}>Size</div>
                        <div>
                            <Button size="xs" className="mx-sm">
                                size xs
                            </Button>
                            <Button size="sm" className="mx-sm">
                                size sm
                            </Button>
                            <Button size="md" className="mx-sm">
                                size md
                            </Button>
                            <Button size="lg" className="mx-sm">
                                size lg
                            </Button>
                            <Button size="xl" className="mx-sm">
                                size xl
                            </Button>
                        </div>
                        <div className={styles.subtitle}>Another</div>
                        <div>
                            <Button loading className="mx-sm">
                                primary
                            </Button>
                            <Button
                                href="https://www.w3schools.com/tags/att_a_href.asp"
                                className="mx-sm"
                            >
                                href
                            </Button>
                        </div>
                    </section>

                    <section className={classNames(styles.section, styles.links)}>
                        <div className={styles.title}>links</div>
                    </section>

                    <section className={classNames(styles.section, styles.inputs)}>
                        <div className={styles.title}>inputs</div>
                        <Row>
                            <Col md={6}>
                                <div className={styles.subtitle}>variant</div>
                                <Flex direction="column" gapY="lg" className="mb-lg">
                                    <Flex gapX="xs">
                                        <div>
                                            <Input placeholder="borderless" variant="borderless" />
                                        </div>
                                        <div>
                                            <Input
                                                placeholder="borderless"
                                                variant="borderless"
                                                error="Пример ошибки валидации"
                                            />
                                        </div>
                                    </Flex>
                                    <Flex gapX="xs">
                                        <div>
                                            <Input placeholder="outlined" variant="outlined" />
                                        </div>
                                        <div>
                                            <Input
                                                placeholder="outlined"
                                                variant="outlined"
                                                error="Пример ошибки валидации"
                                            />
                                        </div>
                                    </Flex>
                                    <Flex gapX="xs">
                                        <div>
                                            <Input placeholder="filled" variant="filled" />
                                        </div>
                                        <div>
                                            <Input
                                                placeholder="filled"
                                                variant="filled"
                                                error="Пример ошибки валидации"
                                            />
                                        </div>
                                    </Flex>
                                </Flex>
                            </Col>
                            <Col md={6}>
                                <div className={styles.subtitle}>another</div>
                                <Flex gapX="xs">
                                    <div>
                                        <InputNumber />
                                    </div>
                                </Flex>
                            </Col>
                        </Row>
                    </section>

                    <section className={classNames(styles.section, styles.chips)}>
                        <div className={styles.title}>chips</div>
                        <div>
                            <Chip color="primary" className="mx-sm">
                                primary
                            </Chip>
                            <Chip color="secondary" className="mx-sm">
                                secondary
                            </Chip>
                            <Chip color="success" className="mx-sm">
                                success
                            </Chip>
                            <Chip color="danger" className="mx-sm">
                                danger
                            </Chip>
                            <Chip color="info" className="mx-sm">
                                info
                            </Chip>
                        </div>
                    </section>

                    <section className={classNames(styles.section, styles.tooltips)}>
                        <div className={styles.title}>tooltips</div>
                    </section>

                    <section className={classNames(styles.section, styles.alerts)}>
                        <div className={styles.title}>alerts</div>
                    </section>

                    <section className={classNames(styles.section, styles.loading)}>
                        <div className={styles.title}>loading</div>
                    </section>

                    <section className={classNames(styles.section, styles.table)}>
                        <div className={styles.title}>table</div>
                        <Table
                            columns={[
                                {
                                    title: 'Title 1',
                                    render: ({ field1 }) => field1,
                                },
                                {
                                    title: 'Title 2',
                                    render: ({ field2 }) => field2,
                                },
                                {
                                    title: 'Title 3',
                                    render: ({ field3 }) => field3,
                                },
                                {
                                    title: 'Title 4',
                                    render: ({ field4 }) => field4,
                                },
                            ]}
                            data={Array(10).fill({
                                field1: 1,
                                field2: 2,
                                field3: 3,
                                field4: 4,
                            })}
                        />
                    </section>
                </div>
            </Container>
        </main>
    );
}
